# Generated by Django 2.1 on 2018-10-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbj', '0002_premio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('valor_en_puntos', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
