# Generated by Django 2.1 on 2018-10-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbj', '0003_logro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.TextField()),
                ('fecha_obtencion', models.DateField(max_length=200)),
            ],
        ),
    ]
